user_infra = "user@example.com"
url_infra = "https://infra.mail.ru:44444/v3/"
pass_infra = "******************************"
domain_id_infra = "default"
tenant_id_infra = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
instance_name = "New-App"
