---
- name: Set up multiple authorized keys for extra
  authorized_key:
    user: extra
    state: present
    key: '{{ item }}'
  with_file:
    - authorized_key/ssergeev_id_rsa.pub
    - authorized_key/ameshcheryakov_id_rsa.pub

- name: Copy sudoers.d
  copy:
    src: sudoers.d/extra
    dest: /etc/sudoers.d/ameshcheryakov
    mode: 0644
