---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False


- name: Configure docker-node
  hosts: docker-node
  become: true
  gather_facts: true

  roles:
    # - base-install-python 
    - docker-node
  vars:
    docker_ce_version: "5:18.09.1"
    # gather_facts: true
